services:
  pygeoapi:
    image: geopython/pygeoapi:latest

    container_name: pygeoapi

    ports:
      - 500:80

    volumes:
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml # Config file
      - ./data:/data # Pull data from here
